/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;

/**
 *
 * @author paola
 */
public class Form extends javax.swing.JFrame {

    /**
     * Creates new form Form
     */
    public Form() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        Título = new javax.swing.JLabel();
        ganancias_bruto = new javax.swing.JLabel();
        gastos_op = new javax.swing.JLabel();
        utilidad = new javax.swing.JLabel();
        LG = new javax.swing.JLabel();
        RR = new javax.swing.JLabel();
        LG_bruto = new javax.swing.JLabel();
        RR_bruto = new javax.swing.JLabel();
        RR_op = new javax.swing.JLabel();
        LG_op = new javax.swing.JLabel();
        LG_utilidad = new javax.swing.JLabel();
        RR_utilidad = new javax.swing.JLabel();
        Guardar = new javax.swing.JButton();
        RR1 = new javax.swing.JLabel();
        LG1 = new javax.swing.JLabel();
        RR_bruto1 = new javax.swing.JLabel();
        LG_bruto1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        jSpinner2 = new javax.swing.JSpinner();
        jSpinner3 = new javax.swing.JSpinner();
        jSpinner4 = new javax.swing.JSpinner();
        jSpinner5 = new javax.swing.JSpinner();
        jSpinner6 = new javax.swing.JSpinner();
        jSpinner7 = new javax.swing.JSpinner();
        jSpinner8 = new javax.swing.JSpinner();
        jSpinner9 = new javax.swing.JSpinner();
        jSpinner10 = new javax.swing.JSpinner();
        jSpinner11 = new javax.swing.JSpinner();
        jSpinner12 = new javax.swing.JSpinner();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Título.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Título.setText("Mercado Automotriz en Venezuela");
        jPanel2.add(Título, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        ganancias_bruto.setText("Ganancias en bruto:");
        jPanel2.add(ganancias_bruto, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 150, -1, -1));

        gastos_op.setText("Gastos operativos:");
        jPanel2.add(gastos_op, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 190, -1, -1));

        utilidad.setText("Utilidad total:");
        jPanel2.add(utilidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 230, -1, -1));

        LG.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        LG.setText("Lamborghini");
        jPanel2.add(LG, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 90, -1, -1));

        RR.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        RR.setText("Rolls Royce");
        jPanel2.add(RR, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 90, -1, -1));

        LG_bruto.setText("jLabel4");
        jPanel2.add(LG_bruto, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 150, -1, -1));

        RR_bruto.setText("jLabel4");
        jPanel2.add(RR_bruto, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 150, -1, -1));

        RR_op.setText("jLabel4");
        jPanel2.add(RR_op, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 190, -1, -1));

        LG_op.setText("jLabel4");
        jPanel2.add(LG_op, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 190, -1, -1));

        LG_utilidad.setText("jLabel4");
        jPanel2.add(LG_utilidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 230, -1, -1));

        RR_utilidad.setText("jLabel4");
        jPanel2.add(RR_utilidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 230, -1, -1));

        Guardar.setText("Guardar");
        Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarActionPerformed(evt);
            }
        });
        jPanel2.add(Guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 340, -1, -1));

        RR1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        RR1.setText("Rolls Royce");
        jPanel2.add(RR1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, -1, -1));

        LG1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        LG1.setText("Lamborghini");
        jPanel2.add(LG1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 90, -1, -1));

        RR_bruto1.setText("jLabel4");
        jPanel2.add(RR_bruto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, -1, -1));

        LG_bruto1.setText("jLabel4");
        jPanel2.add(LG_bruto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 120, -1, -1));

        jLabel2.setText("Cantidad de empleados");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        jLabel3.setText("Creadores de chasis");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        jLabel4.setText("Creadores de carrocerías");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));

        jLabel5.setText("Creadores de motores");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, -1));

        jLabel6.setText("Ensambladores");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, -1, -1));
        jPanel2.add(jSpinner1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 150, 40, 20));
        jPanel2.add(jSpinner2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 150, 40, 20));
        jPanel2.add(jSpinner3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, 40, 20));
        jPanel2.add(jSpinner4, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 180, 40, 20));
        jPanel2.add(jSpinner5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 210, 40, 20));
        jPanel2.add(jSpinner6, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 210, 40, 20));
        jPanel2.add(jSpinner7, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 240, 40, 20));
        jPanel2.add(jSpinner8, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 240, 40, 20));
        jPanel2.add(jSpinner9, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 270, 40, 20));
        jPanel2.add(jSpinner10, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 270, 40, 20));
        jPanel2.add(jSpinner11, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 300, 40, 20));
        jPanel2.add(jSpinner12, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 300, 40, 20));

        jLabel7.setText("Creadores de ruedas");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, -1, -1));

        jLabel8.setText("Creadores de accesorios");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, -1, -1));

        jTabbedPane1.addTab("DashBoard", jPanel2);

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jTabbedPane1.addTab("Rolls Royce", jPanel3);

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jTabbedPane1.addTab("Lamborghini", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 904, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 534, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GuardarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Guardar;
    private javax.swing.JLabel LG;
    private javax.swing.JLabel LG1;
    private javax.swing.JLabel LG_bruto;
    private javax.swing.JLabel LG_bruto1;
    private javax.swing.JLabel LG_op;
    private javax.swing.JLabel LG_utilidad;
    private javax.swing.JLabel RR;
    private javax.swing.JLabel RR1;
    private javax.swing.JLabel RR_bruto;
    private javax.swing.JLabel RR_bruto1;
    private javax.swing.JLabel RR_op;
    private javax.swing.JLabel RR_utilidad;
    private javax.swing.JLabel Título;
    private javax.swing.JLabel ganancias_bruto;
    private javax.swing.JLabel gastos_op;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JSpinner jSpinner10;
    private javax.swing.JSpinner jSpinner11;
    private javax.swing.JSpinner jSpinner12;
    private javax.swing.JSpinner jSpinner2;
    private javax.swing.JSpinner jSpinner3;
    private javax.swing.JSpinner jSpinner4;
    private javax.swing.JSpinner jSpinner5;
    private javax.swing.JSpinner jSpinner6;
    private javax.swing.JSpinner jSpinner7;
    private javax.swing.JSpinner jSpinner8;
    private javax.swing.JSpinner jSpinner9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel utilidad;
    // End of variables declaration//GEN-END:variables
}
