/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;

import java.awt.BorderLayout;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JSpinner;
import javax.swing.SpinnerNumberModel;
import proyectoso1.Main;
import proyectoso1.Txt;
import proyectoso1.Values;
/**
 *
 * @author paola
 */
public final class Form extends javax.swing.JFrame {

    private final WorkersQtySpinner wRR;
    private final WorkersQtySpinner wLG;
    private final PlantForm plantRR;
    private final PlantForm plantLG;
    /**
     * Creates new form Form
     */
    public Form() {
        initComponents();
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        this.wLG = new WorkersQtySpinner(Values.maxEmployeesLG, "workersLG");
        this.wRR = new WorkersQtySpinner(Values.maxEmployeesRR, "workersRR");
        createWorkersQtySpinner(contentLG, wLG);
        createWorkersQtySpinner(contentRR, wRR);
        createModelSpinner(DayDurationSpinner, "DayDurationSpinner");
        createModelSpinner(DeadlineSpinner, "DeadlineSpinner");
        this.plantRR = new PlantForm(false);
        createPlant(RRPanel, plantRR);
        this.plantLG = new PlantForm(true);
        createPlant(LGPanel, plantLG);
    }
    
    public void createPlant(JPanel panel, PlantForm pq){
        pq.setSize(773, 400);
        pq.setLocation(0, 0);
        panel.removeAll();
        panel.add(pq, BorderLayout.CENTER);
        panel.revalidate();
        panel.repaint();
    }
    
    public void createWorkersQtySpinner(JPanel panel, WorkersQtySpinner wq){
        wq.setSize(60, 220);
        wq.setLocation(0, 0);
        panel.removeAll();
        panel.add(wq, BorderLayout.CENTER);
        panel.revalidate();
        panel.repaint();
    }
       
    public void createModelSpinner(JSpinner spinner, String label){
        SpinnerNumberModel nm = new SpinnerNumberModel();
        nm.setMinimum(1);
        if (label.equals("DayDurationSpinner")){
            nm.setValue(Main.initial.dayDuration/1000);
        }else if (label.equals("DeadlineSpinner")){
            nm.setValue(Main.initial.deadLine/1000);
        }
        spinner.setModel(nm);
    }    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        RRPanel = new javax.swing.JPanel();
        LGPanel = new javax.swing.JPanel();
        DashBoard_Panel = new javax.swing.JPanel();
        contentRR = new javax.swing.JPanel();
        Título = new javax.swing.JLabel();
        ganancias_bruto = new javax.swing.JLabel();
        gastos_op = new javax.swing.JLabel();
        utilidad = new javax.swing.JLabel();
        LG = new javax.swing.JLabel();
        RR = new javax.swing.JLabel();
        LG_bruto = new javax.swing.JLabel();
        RR_bruto = new javax.swing.JLabel();
        RR_op = new javax.swing.JLabel();
        LG_op = new javax.swing.JLabel();
        LG_utilidad = new javax.swing.JLabel();
        RR_utilidad = new javax.swing.JLabel();
        Guardar = new javax.swing.JButton();
        RR1 = new javax.swing.JLabel();
        LG1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        Deadline = new javax.swing.JLabel();
        DayDuration = new javax.swing.JLabel();
        DeadlineSpinner = new javax.swing.JSpinner();
        DayDurationSpinner = new javax.swing.JSpinner();
        contentLG = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        RRPanel.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout RRPanelLayout = new javax.swing.GroupLayout(RRPanel);
        RRPanel.setLayout(RRPanelLayout);
        RRPanelLayout.setHorizontalGroup(
            RRPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 773, Short.MAX_VALUE)
        );
        RRPanelLayout.setVerticalGroup(
            RRPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 412, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Rolls Royce", RRPanel);

        LGPanel.setBackground(new java.awt.Color(255, 255, 255));
        LGPanel.setRequestFocusEnabled(false);

        javax.swing.GroupLayout LGPanelLayout = new javax.swing.GroupLayout(LGPanel);
        LGPanel.setLayout(LGPanelLayout);
        LGPanelLayout.setHorizontalGroup(
            LGPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 773, Short.MAX_VALUE)
        );
        LGPanelLayout.setVerticalGroup(
            LGPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 412, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Lamborghini", LGPanel);

        DashBoard_Panel.setBackground(new java.awt.Color(255, 255, 255));
        DashBoard_Panel.setPreferredSize(new java.awt.Dimension(773, 412));
        DashBoard_Panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        contentRR.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout contentRRLayout = new javax.swing.GroupLayout(contentRR);
        contentRR.setLayout(contentRRLayout);
        contentRRLayout.setHorizontalGroup(
            contentRRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );
        contentRRLayout.setVerticalGroup(
            contentRRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 220, Short.MAX_VALUE)
        );

        DashBoard_Panel.add(contentRR, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, 60, 220));

        Título.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Título.setText("Mercado Automotriz en Venezuela");
        DashBoard_Panel.add(Título, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        ganancias_bruto.setText("Ganancias en bruto:");
        DashBoard_Panel.add(ganancias_bruto, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 150, -1, -1));

        gastos_op.setText("Gastos operativos:");
        DashBoard_Panel.add(gastos_op, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 190, -1, -1));

        utilidad.setText("Utilidad total:");
        DashBoard_Panel.add(utilidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 230, -1, -1));

        LG.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        LG.setText("Lamborghini");
        DashBoard_Panel.add(LG, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 90, -1, -1));

        RR.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        RR.setText("Rolls Royce");
        DashBoard_Panel.add(RR, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 90, -1, -1));

        LG_bruto.setText("0");
        DashBoard_Panel.add(LG_bruto, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 150, 80, -1));

        RR_bruto.setText("0");
        DashBoard_Panel.add(RR_bruto, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 150, 80, -1));

        RR_op.setText("0");
        DashBoard_Panel.add(RR_op, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 190, 80, -1));

        LG_op.setText("0");
        DashBoard_Panel.add(LG_op, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 190, 80, -1));

        LG_utilidad.setText("0");
        DashBoard_Panel.add(LG_utilidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 230, 80, -1));

        RR_utilidad.setText("0");
        DashBoard_Panel.add(RR_utilidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 230, 80, -1));

        Guardar.setText("Guardar");
        Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarActionPerformed(evt);
            }
        });
        DashBoard_Panel.add(Guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 360, -1, -1));

        RR1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        RR1.setText("Rolls Royce");
        DashBoard_Panel.add(RR1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, -1, -1));

        LG1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        LG1.setText("Lamborghini");
        DashBoard_Panel.add(LG1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 90, -1, -1));

        jLabel2.setText("Empleados disponibles");
        DashBoard_Panel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        jLabel3.setText("Creadores de chasis");
        DashBoard_Panel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        jLabel4.setText("Creadores de carrocerías");
        DashBoard_Panel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));

        jLabel5.setText("Creadores de motores");
        DashBoard_Panel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, -1));

        jLabel7.setText("Creadores de ruedas");
        DashBoard_Panel.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, -1, -1));

        jLabel8.setText("Creadores de accesorios");
        DashBoard_Panel.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, -1, -1));

        jLabel9.setText("Ensambladores");
        DashBoard_Panel.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, -1, -1));

        Deadline.setText("Deadline de entrega (en segundos):");
        DashBoard_Panel.add(Deadline, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, -1, -1));

        DayDuration.setText("Duración del día (en segundos):");
        DashBoard_Panel.add(DayDuration, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, -1, -1));

        DeadlineSpinner.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));
        DashBoard_Panel.add(DeadlineSpinner, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 380, 40, -1));

        DayDurationSpinner.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));
        DashBoard_Panel.add(DayDurationSpinner, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 350, 40, -1));

        contentLG.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout contentLGLayout = new javax.swing.GroupLayout(contentLG);
        contentLG.setLayout(contentLGLayout);
        contentLGLayout.setHorizontalGroup(
            contentLGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );
        contentLGLayout.setVerticalGroup(
            contentLGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 220, Short.MAX_VALUE)
        );

        DashBoard_Panel.add(contentLG, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 110, 60, 220));

        jTabbedPane1.addTab("DashBoard", DashBoard_Panel);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 440));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarActionPerformed
        // TODO add your handling code here:
        Main.initial.setDayDuration(((int)DayDurationSpinner.getValue())*1000);
        Main.initial.setDeadLine(((int)DeadlineSpinner.getValue())*1000);
        Main.initial.setWorkersRR(this.wRR.valuesSpinners);
        Main.initial.setWorkersLG(this.wLG.valuesSpinners);
        plantLG.getWqLG().update(Main.initial.workersLG);
        plantRR.getWqLG().update(Main.initial.workersRR);
        Txt.saveData();
        Main.LGPlant.initializeWorkers();
        Main.RRPlant.initializeWorkers();
        int dayDuration = Main.initial.getDayDuration();
        
        Main.LGPlant.setDayDuration(dayDuration);
        Main.LGPlant.setCounterDaysDelivery(Main.initial.getDeadLine());
        Main.LGPlant.initializeOther();
        
        Main.RRPlant.setDayDuration(dayDuration);
        Main.RRPlant.setCounterDaysDelivery(Main.initial.getDeadLine());
        Main.RRPlant.initializeOther();
        
    }//GEN-LAST:event_GuardarActionPerformed

   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form().setVisible(true);
            }
        });
    }

    public JLabel getDirectorIsLG() {
        return plantLG.getDirectorIsLG();
    }

    public JLabel getFaultsLG() {
        return plantLG.getFaultsLG();
    }

    public JLabel getManagerIsLG() {
        return plantLG.getManagerIsLG();
    }

    public JLabel getPenaltyLG() {
        return plantLG.getPenaltyLG();
    }
    
    public JLabel getVaLG() {
        return plantLG.getVaLG();
    }

    public JLabel getVeLG() {
        return plantLG.getVeLG();
    }

    public PartsQty getPartsLG() {
        return plantLG.getPartsLG();
    }
    
    public JLabel getDaysLeftLG() {
        return plantLG.getDaysLeftLG();
    }
    
      
    
    
    public JLabel getDirectorIsRR() {
        return plantRR.getDirectorIsLG();
    }

    public JLabel getFaultsRR() {
        return plantRR.getFaultsLG();
    }

    public JLabel getManagerIsRR() {
        return plantRR.getManagerIsLG();
    }

    public JLabel getPenaltyRR() {
        return plantRR.getPenaltyLG();
    }
    
    public JLabel getVaRR() {
        return plantRR.getVaLG();
    }

    public JLabel getVeRR() {
        return plantRR.getVeLG();
    }

    public PartsQty getPartsRR() {
        return plantRR.getPartsLG();
    }
    
    public JLabel getDaysLeftRR() {
        return plantRR.getDaysLeftLG();
    }

    public JLabel getLG_bruto() {
        return LG_bruto;
    }

    public JLabel getLG_op() {
        return LG_op;
    }

    public JLabel getLG_utilidad() {
        return LG_utilidad;
    }

    public JLabel getRR_bruto() {
        return RR_bruto;
    }

    public JLabel getRR_op() {
        return RR_op;
    }

    public JLabel getRR_utilidad() {
        return RR_utilidad;
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel DashBoard_Panel;
    private javax.swing.JLabel DayDuration;
    private javax.swing.JSpinner DayDurationSpinner;
    private javax.swing.JLabel Deadline;
    private javax.swing.JSpinner DeadlineSpinner;
    private javax.swing.JButton Guardar;
    private javax.swing.JLabel LG;
    private javax.swing.JLabel LG1;
    private javax.swing.JPanel LGPanel;
    private javax.swing.JLabel LG_bruto;
    private javax.swing.JLabel LG_op;
    private javax.swing.JLabel LG_utilidad;
    private javax.swing.JLabel RR;
    private javax.swing.JLabel RR1;
    private javax.swing.JPanel RRPanel;
    private javax.swing.JLabel RR_bruto;
    private javax.swing.JLabel RR_op;
    private javax.swing.JLabel RR_utilidad;
    private javax.swing.JLabel Título;
    private javax.swing.JPanel contentLG;
    private javax.swing.JPanel contentRR;
    private javax.swing.JLabel ganancias_bruto;
    private javax.swing.JLabel gastos_op;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel utilidad;
    // End of variables declaration//GEN-END:variables
}
