/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;

import javax.swing.JLabel;

/**
 *
 * @author paola
 */
public class PartsQty extends javax.swing.JPanel {

    private final JLabel[] labels;
    

    /**
     * Creates new form PartsQty
     */
    public PartsQty() {
        initComponents();
        this.labels = new JLabel[5];
        initializeLabels();
    }
    
    public final void initializeLabels(){
        this.labels[0] = this.chasis;
        this.labels[1] = this.body;
        this.labels[2] = this.engine;
        this.labels[3] = this.wheels;
        this.labels[4] = this.acc;
    }
    
    public void update(int[] array){
        for (int i = 0; i < array.length; i++) {
            this.labels[i].setText(String.valueOf(array[i]));
        }
    }

    public JLabel[] getLabels() {
        return labels;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        chasis = new javax.swing.JLabel();
        body = new javax.swing.JLabel();
        engine = new javax.swing.JLabel();
        wheels = new javax.swing.JLabel();
        acc = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        chasis.setText("0");
        chasis.setMaximumSize(new java.awt.Dimension(20, 14));
        chasis.setPreferredSize(new java.awt.Dimension(20, 14));
        jPanel1.add(chasis, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        body.setText("0");
        body.setMaximumSize(new java.awt.Dimension(20, 14));
        body.setPreferredSize(new java.awt.Dimension(20, 14));
        jPanel1.add(body, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        engine.setText("0");
        engine.setMaximumSize(new java.awt.Dimension(20, 14));
        engine.setPreferredSize(new java.awt.Dimension(20, 14));
        jPanel1.add(engine, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 20, -1));

        wheels.setText("0");
        wheels.setMaximumSize(new java.awt.Dimension(20, 14));
        wheels.setPreferredSize(new java.awt.Dimension(20, 14));
        jPanel1.add(wheels, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 20, -1));

        acc.setText("0");
        acc.setMaximumSize(new java.awt.Dimension(20, 14));
        acc.setPreferredSize(new java.awt.Dimension(20, 14));
        jPanel1.add(acc, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 359, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 146, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel acc;
    private javax.swing.JLabel body;
    private javax.swing.JLabel chasis;
    private javax.swing.JLabel engine;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel wheels;
    // End of variables declaration//GEN-END:variables
}
