/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;

import java.awt.BorderLayout;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JSpinner;
import javax.swing.SpinnerNumberModel;
import proyectoso1.Main;
import proyectoso1.Values;

/**
 *
 * @author paola
 */
public class PlantForm extends javax.swing.JPanel {
    
    private WorkersQtySpinner wLG;
    private MaxView maxView; 
    private WorkersQty wqLG;
    private PartsQty partsLG;
//    private PartsQty partsRR;
//    private WorkersQty wqRR;
//    private WorkersQtySpinner wRR;
    
    /**
     * Creates new form PlantForm
     * @param isLG
     */
    public PlantForm(boolean isLG) {
        initComponents();
        if (isLG){
            this.wLG = new WorkersQtySpinner(Values.maxEmployeesLG, "workersLG");
            fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/rsz_carros.jpg")));
        }else{
            this.wLG = new WorkersQtySpinner(Values.maxEmployeesRR, "workersRR");
            fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/rsz_rrfondo_2.jpg")));
        }
        this.maxView = new MaxView();
        this.wqLG = new WorkersQty();
        this.partsLG = new PartsQty();
        createMax(maxLG);
        if (isLG){
            Título1.setText("Lamborghini");
            wqLG.update(Main.initial.getWorkersLG());
            createWorkersQty(workersQtyLG, wqLG);
            createPartsQty(partsQtyLG, partsLG);
        }else{
            Título1.setText("Rolls Royce");
            wqLG.update(Main.initial.getWorkersRR());
            createWorkersQty(workersQtyLG, wqLG);
            createPartsQty(partsQtyLG, partsLG);
        }
    }

        public void createPartsQty(JPanel panel, PartsQty pq){
        pq.setSize(60, 220);
        pq.setLocation(0, 0);
        panel.removeAll();
        panel.add(pq, BorderLayout.CENTER);
        panel.revalidate();
        panel.repaint();
    }
        
    public void createWorkersQty(JPanel panel, WorkersQty wq){
        wq.setSize(60, 220);
        wq.setLocation(0, 0);
        panel.removeAll();
        panel.add(wq, BorderLayout.CENTER);
        panel.revalidate();
        panel.repaint();
    }
    public void createMax(JPanel panel){
        maxView.setSize(60,220);
        maxView.setLocation(0,0);
        panel.removeAll();
        panel.add(maxView, BorderLayout.CENTER);
        panel.revalidate();
        panel.repaint();
    }

    public JLabel getDaysLeftLG() {
        return daysLeftLG;
    }
    
    public JLabel getDirectorIsLG() {
        return directorIsLG;
    }

    public JLabel getFaultsLG() {
        return faultsLG;
    }

    public JLabel getManagerIsLG() {
        return managerIsLG;
    }

    public JLabel getPenaltyLG() {
        return penaltyLG;
    }
    
    public JLabel getVaLG() {
        return vaLG;
    }

    public JLabel getVeLG() {
        return veLG;
    }

    public PartsQty getPartsLG() {
        return partsLG;
    }

    public WorkersQty getWqLG() {
        return wqLG;
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        workersQtyLG = new javax.swing.JPanel();
        jLabel45 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        partsQtyLG = new javax.swing.JPanel();
        maxLG = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        directorIsLG = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        managerIsLG = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        faultsLG = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        penaltyLG = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        veLG = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        vaLG = new javax.swing.JLabel();
        Título1 = new javax.swing.JLabel();
        daysLeftLG = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(773, 412));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel26.setText("Cantidad de trabajadores:");
        jPanel1.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        jLabel6.setText("Creadores de chasis");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, -1, -1));

        jLabel10.setText("Creadores de carrocerías");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, -1, -1));

        jLabel11.setText("Creadores de motores");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, -1, -1));

        jLabel12.setText("Creadores de ruedas");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, -1, -1));

        jLabel13.setText("Creadores de accesorios");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, -1, -1));

        jLabel14.setText("Ensambladores");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, -1, -1));

        workersQtyLG.setBackground(new java.awt.Color(255, 255, 255));
        workersQtyLG.setOpaque(false);
        workersQtyLG.setPreferredSize(new java.awt.Dimension(44, 174));

        javax.swing.GroupLayout workersQtyLGLayout = new javax.swing.GroupLayout(workersQtyLG);
        workersQtyLG.setLayout(workersQtyLGLayout);
        workersQtyLGLayout.setHorizontalGroup(
            workersQtyLGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );
        workersQtyLGLayout.setVerticalGroup(
            workersQtyLGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 190, Short.MAX_VALUE)
        );

        jPanel1.add(workersQtyLG, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 90, 60, 190));

        jLabel45.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel45.setText("Cantidad de partes:");
        jPanel1.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 70, -1, -1));

        jLabel38.setText("Producidas");
        jPanel1.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 100, -1, -1));

        partsQtyLG.setBackground(new java.awt.Color(255, 255, 255));
        partsQtyLG.setOpaque(false);
        partsQtyLG.setPreferredSize(new java.awt.Dimension(40, 144));

        javax.swing.GroupLayout partsQtyLGLayout = new javax.swing.GroupLayout(partsQtyLG);
        partsQtyLG.setLayout(partsQtyLGLayout);
        partsQtyLGLayout.setHorizontalGroup(
            partsQtyLGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );
        partsQtyLGLayout.setVerticalGroup(
            partsQtyLGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 144, Short.MAX_VALUE)
        );

        jPanel1.add(partsQtyLG, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 120, -1, -1));

        maxLG.setBackground(new java.awt.Color(255, 255, 255));
        maxLG.setOpaque(false);
        maxLG.setPreferredSize(new java.awt.Dimension(46, 174));

        javax.swing.GroupLayout maxLGLayout = new javax.swing.GroupLayout(maxLG);
        maxLG.setLayout(maxLGLayout);
        maxLGLayout.setHorizontalGroup(
            maxLGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );
        maxLGLayout.setVerticalGroup(
            maxLGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 174, Short.MAX_VALUE)
        );

        jPanel1.add(maxLG, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 90, 70, -1));

        jLabel21.setText("Chasis");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 130, -1, -1));

        jLabel22.setText("Carrocerías");
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 160, -1, -1));

        jLabel23.setText("Motores");
        jPanel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 190, -1, -1));

        jLabel24.setText("Ruedas");
        jPanel1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 220, -1, -1));

        jLabel25.setText("Accesorios");
        jPanel1.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 250, -1, -1));

        jLabel46.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel46.setText("Información sobre el gerente");
        jPanel1.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 150, -1, -1));

        jLabel48.setText("El director está");
        jPanel1.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 110, -1, -1));

        directorIsLG.setText("Working");
        jPanel1.add(directorIsLG, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 110, -1, -1));

        jLabel51.setText("El gerente está");
        jPanel1.add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 190, -1, -1));

        managerIsLG.setText("Working");
        jPanel1.add(managerIsLG, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 190, -1, -1));

        jLabel47.setText("Cantidad de faltas:");
        jPanel1.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 220, -1, -1));

        faultsLG.setText("0");
        jPanel1.add(faultsLG, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 220, 50, -1));

        jLabel53.setText("Dinero descontado:");
        jPanel1.add(jLabel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 250, -1, -1));

        penaltyLG.setText("0");
        jPanel1.add(penaltyLG, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 250, 50, -1));

        jLabel43.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/calendar_today_FILL0_wght400_GRAD0_opsz48.png"))); // NOI18N
        jLabel43.setText("días restantes para la entrega");
        jPanel1.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 310, 230, 60));

        jLabel39.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel39.setText("Vehículos estándar");
        jPanel1.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, -1, -1));

        veLG.setText("0");
        jPanel1.add(veLG, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 320, 30, -1));

        jLabel42.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel42.setText("Vehículos con accesorios");
        jPanel1.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, -1, -1));

        vaLG.setText("0");
        jPanel1.add(vaLG, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 350, 30, -1));

        Título1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Título1.setText("MARCA");
        jPanel1.add(Título1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 20, -1, -1));

        daysLeftLG.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        daysLeftLG.setText("0");
        jPanel1.add(daysLeftLG, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 340, 50, -1));

        jLabel49.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel49.setText("Información sobre el director");
        jPanel1.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 70, -1, -1));
        jPanel1.add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Título1;
    private javax.swing.JLabel daysLeftLG;
    private javax.swing.JLabel directorIsLG;
    private javax.swing.JLabel faultsLG;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel managerIsLG;
    private javax.swing.JPanel maxLG;
    private javax.swing.JPanel partsQtyLG;
    private javax.swing.JLabel penaltyLG;
    private javax.swing.JLabel vaLG;
    private javax.swing.JLabel veLG;
    private javax.swing.JPanel workersQtyLG;
    // End of variables declaration//GEN-END:variables
}
