/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;

import javax.swing.JLabel;

/**
 *
 * @author paola
 */
public class WorkersQty extends javax.swing.JPanel {

    private final JLabel[] labels;
    /**
     * Creates new form WorkersQty
     */
    public WorkersQty() {
        initComponents();
        this.labels = new JLabel[6];
        initializeLabels();
    }
    
    public final void initializeLabels(){
        this.labels[0] = this.workersChasis;
        this.labels[1] = this.workersBody;
        this.labels[2] = this.workersEngine;
        this.labels[3] = this.workersWheels;
        this.labels[4] = this.workersAcc;
        this.labels[5] = this.workersAssembler;
    }
    
    public void update(int[] array){
        for (int i = 0; i < array.length; i++) {
            this.labels[i].setText(String.valueOf(array[i]));
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        workersChasis = new javax.swing.JLabel();
        workersBody = new javax.swing.JLabel();
        workersEngine = new javax.swing.JLabel();
        workersWheels = new javax.swing.JLabel();
        workersAcc = new javax.swing.JLabel();
        workersAssembler = new javax.swing.JLabel();

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        workersChasis.setText("jLabel1");
        jPanel1.add(workersChasis, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        workersBody.setText("jLabel1");
        jPanel1.add(workersBody, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        workersEngine.setText("jLabel1");
        jPanel1.add(workersEngine, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        workersWheels.setText("jLabel1");
        jPanel1.add(workersWheels, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        workersAcc.setText("jLabel1");
        jPanel1.add(workersAcc, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        workersAssembler.setText("jLabel1");
        jPanel1.add(workersAssembler, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 40, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel workersAcc;
    private javax.swing.JLabel workersAssembler;
    private javax.swing.JLabel workersBody;
    private javax.swing.JLabel workersChasis;
    private javax.swing.JLabel workersEngine;
    private javax.swing.JLabel workersWheels;
    // End of variables declaration//GEN-END:variables
}
